### PR TITLE
Force published field

### LINKED ISSUE #146: Populate "Published" field when only "Updated" exists
### Expected behavior

_Published_ should always be populated as it's used for comparison, etc.

### Actual behavior

If a feed only have _updated_ field, _Published_ stay `nil`.

### Steps to reproduce the behavior

feeds:
- https://cloud.google.com/feeds/kubernetes-engine-release-notes.xml
- https://github.com/Azure/AKS/releases.atom (and all github feeds)

### PR DESCRIPTION
**Pull request by guilhem**
When an atom item only have updated field, use it to fill published.

- Less function is using published field, it has to always been
populated.
- Simplify code when using both RSS and Atom feeds.

This fix #146

### CODE REVIEW

File: translator.go [hunk 1]
```diff
@@ -608,11 +608,19 @@ func (t *DefaultAtomTranslator) translateItemUpdatedParsed(entry *atom.Entry) (u
 }
 
 func (t *DefaultAtomTranslator) translateItemPublished(entry *atom.Entry) (updated string) {
-	return entry.Published
+	updated = entry.Published
```
Comment (Necoro) [inline translator.go:611]: While not your fault, it would be nice to rename the variable `updated` to `published` to know what is going on here. I was slightly puzzled reading the code :)

Comment (guilhem) [reply translator.go]: Done :)

**Comment by guilhem** [comment]
@mmcdole gentle ping :)

**Review by mmcdole — APPROVED** [review]

**Comment by mmcdole** [comment]
Thanks for the contribution @guilhem
